twilio: # Twilio gateway configuration
  accountId:    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  accountToken: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  localDomain:  cds.konglomerat.net
  numbers:
    - "+11111111111"
  messagingServicesId: ""

push:
  queueSize: 200

turn: # TURN server configuration
  secret: test
  uris:
    - turn:127.0.0.1:3478?transport=udp

cache: # Redis server configuration for cache cluster
  url: redis://127.0.0.1:6379/cache
  replicaUrls:
    -  redis://127.0.0.1:6379/cacheReplica

directory:
  redis: # Redis server configuration for directory cluster
    url: redis://127.0.0.1:6379/directory
    replicaUrls:
      -  redis://127.0.0.1:6379/directoryReplica
  client: # Configuration for interfacing with Contact Discovery Service cluster
    userAuthenticationTokenSharedSecret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    userAuthenticationTokenUserIdSecret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  sqs:
    accessKey:    AAAAAAAAAAAAAAAAAAAA
    accessSecret: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    queueUrl:     https://sqs.ap-southeast-1.amazonaws.com/111111111111/konglomerat-queue
  server:
    replicationUrl: http://127.0.0.1:9090 # CDS replication endpoint base url
    replicationPassword:      mypassword # CDS replication endpoint password
    replicationCaCertificate: |
      -----BEGIN CERTIFICATE-----
      MIIGDzCCA/egAwIBAgIUUmP5XBG9pEmYwiUblNg99VS6msAwDQYJKoZIhvcNAQEL
      BQAwgZYxCzAJBgNVBAYTAlNHMRIwEAYDVQQIDAlTaW5nYXBvcmUxEjAQBgNVBAcM
      ................................................................
      X/XgYucvAxW+btWOVNT0C8ZOBxujxeqCE4cSeRYq/uq9iopMqc6rZDjI61o6l5f2
      n9l4ST32vI9VjA5BdB/YQ+e2QEruRdBH3+l0n+jWr+8yT8FE4iW0Ey6j4dT2QefF
      LTZidTSgjz/RaWNgQ7ucclaoew==
      -----END CERTIFICATE-----
    #reconciliationChunkSize:           10 # CDS reconciliation chunk size
    #reconciliationChunkIntervalMs: 300000 # Setiap 5 menit

messageCache: # Redis server configuration for message store cache
  redis:
    url: redis://127.0.0.1:6379/messageCache
    replicaUrls:
      -  redis://127.0.0.1:6379/messageCacheReplica

attachments: # AWS S3 configuration
  accessKey:    AAAAAAAAAAAAAAAAAAAA
  accessSecret: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  bucket:       konglomerat-bucket
  region:       ap-southeast-1

profiles: # AWS S3 configuration
  accessKey:    AAAAAAAAAAAAAAAAAAAA
  accessSecret: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  bucket:       konglomerat-bucket
  region:       ap-southeast-1

database:
  driverClass: org.postgresql.Driver
  user:        konglomerat
  password:    konglomerat
  url:         jdbc:postgresql://127.0.0.1:5432/konglomerat

messageStore:
  driverClass: org.postgresql.Driver
  user:        konglomerat
  password:    konglomerat
  url:         jdbc:postgresql://127.0.0.1:5433/konglomerat

abuseDatabase:
  driverClass: org.postgresql.Driver
  user:        konglomerat
  password:    konglomerat
  url:         jdbc:postgresql://127.0.0.1:5434/konglomerat

gcm:
  senderId: 11111111111
  apiKey:   AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

recaptcha:
  secret: asdf

accountDatabaseCrawler:
  chunkSize:       1000
  chunkIntervalMs: 1000000

apn:
  pushCertificate: |
    -----BEGIN CERTIFICATE-----
    MIIF0zCCBLugAwIBAgIBATANBgkqhkiG9w0BAQsFADBiMRwwGgYDVQQDDBNBcHBs
    ZSBJU1QgQ0EgMiAtIEcxMSAwHgYDVQQLDBdDZXJ0aWZpY2F0aW9uIEF1dGhvcml0
    ................................................................
    5xBrwcth3nwD8vtEZxXP/N9/wzT6SU+M4ZP0bOuU7TjRWjMEjkjlaCrXyj9LhO6d
    h5XraaY8X1Ga1LKC8bvRGsQSCQ+GOcwNQDTXeyluFghaJVooZ327pKnfqfCaatgI
    82f0IgKrMg==
    -----END CERTIFICATE-----

  pushKey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAtXd9zNAVgmJpPOBbw+csH+Eld6R24CJgwpLKbK9dwJlw7GpH
    pz2z7YuZ0Y4vzVcSSXr6RgWQEZfI413uuk7vvekwIKFg8ZzBxNtA8t3rTaEiWPbL
    ................................................................
    +69opYrJTZmpfdEB+WClNAG3Df43a57o9W/Nvm4i83X9YHTAi2V7dlBnTTfJliqF
    ZXU5fOMn3EWtofyuKDTDKOfocHPt6dLvxv+wN7IXY9fCp7jOwYQbSw==
    -----END RSA PRIVATE KEY-----

  bundleId: com.konglomerat
  sandbox: true

unidentifiedDelivery:
  certificate: CiUIDBIhBbTz4h1My+tt+vw+TVscgUe/DeHS0W02tPWAWbTO2xc3EkD+go4bJnU0AcnFfbOLKoiBfCzouZtDYMOVi69rE7r4U9cXREEqOkUmU2WJBjykAxWPCcSTmVTYHDw7hkSp/puG
  privateKey:  ABOxG29xrfq4E7IrW11Eg7+HBbtba9iiS0500YoBjn4=
  expiresDays: 100

voiceVerification:
  url: https://server.konglomerat.net
  locales:
    - en

pushScheduler:
  url: redis://127.0.0.1:6379/pushScheduler
  replicaUrls:
    - redis://127.0.0.1:6379/pushSchedulerReplica
  circuitBreaker:
    failureRateThreshold: 50
    ringBufferSizeInHalfOpenState: 10
    ringBufferSizeInClosedState: 100
    waitDurationInOpenStateInSeconds: 10

### END : not listed at original YML config file

server:
  applicationConnectors:
    - type: http
      port: 8000
  adminConnectors:
    - type: http
      port: 8001
